replicaCount: 2

image:
  repository: docker.aa.com/nonprod/fxip/fxip-data-lineage-tool
  tag: "stage"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  hosts:
    - host: fxip-lineage.stage.internal.aa.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fxip-lineage-stage-tls
      hosts:
        - fxip-lineage.stage.internal.aa.com

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi
